# Generated by Django 4.2.5 on 2023-09-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reporter_id',
            field=models.CharField(max_length=20),
        ),
    ]
